# Generated by Django 3.2.19 on 2023-06-22 17:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://static.vecteezy.com/system/resources/previews/003/718/594/original/avatar-contact-media-free-vector.jpg', max_length=255, verbose_name='image'),
        ),
    ]
