# Generated by Django 3.2.19 on 2023-06-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_privatecontactlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatecontactlist',
            old_name='User_name',
            new_name='user_name',
        ),
    ]
