# Generated by Django 3.2.19 on 2023-06-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0006_rename_user_name_privatecontactlist_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatecontactlist',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
