# Generated by Django 3.2.19 on 2023-06-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_alter_privatecontactlist_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatecontactlist',
            name='user_name',
        ),
    ]
