# Generated by Django 3.2.19 on 2023-06-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_remove_privatecontactlist_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateContactList',
        ),
    ]
